# Generated by Django 5.1.8 on 2025-04-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
